// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2GjeMi4miGVKktyt-PEfnQtaq3xujQp4',
    appId: '1:1036709275135:web:99d86ae8a1a7b4f924b3ca',
    messagingSenderId: '1036709275135',
    projectId: 'finger-print-app-9f84a',
    authDomain: 'finger-print-app-9f84a.firebaseapp.com',
    storageBucket: 'finger-print-app-9f84a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSte0IM60WKydsTj_X4qCVB5ch6WZz-OE',
    appId: '1:1036709275135:android:fa44214c94d81e2424b3ca',
    messagingSenderId: '1036709275135',
    projectId: 'finger-print-app-9f84a',
    storageBucket: 'finger-print-app-9f84a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA40apGmirQrBobhueHjEHHPQ5tzFDX4c0',
    appId: '1:1036709275135:ios:178a6f7576c2e0f824b3ca',
    messagingSenderId: '1036709275135',
    projectId: 'finger-print-app-9f84a',
    storageBucket: 'finger-print-app-9f84a.appspot.com',
    iosBundleId: 'com.example.fingerPrintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA40apGmirQrBobhueHjEHHPQ5tzFDX4c0',
    appId: '1:1036709275135:ios:61b9a7a9569e6c7924b3ca',
    messagingSenderId: '1036709275135',
    projectId: 'finger-print-app-9f84a',
    storageBucket: 'finger-print-app-9f84a.appspot.com',
    iosBundleId: 'com.example.fingerPrintApp.RunnerTests',
  );
}
